import './globals.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Your Name" />
        <meta name="keywords" content="Next.js, React, App" />
      </head>
      <body>{children}</body>
    </html>
  )
}